= Contribute (Asciidoc)

JDBC over SSH…

== Issues (bug and feature tracker)

Please report any bugs found, feature requests or other issues on
https://github.com/monkeysintown/jdbc-ssh/issues/[JDBC SSH GitHub tracker].

When creating a new issue, try following http://github.com/necolas/issue-guidelines/#readme[necolas's guidelines].

== Fork, patch and contribute code

Feel free to fork Reflow skin's https://github.com/monkeysintown/jdbc-ssh[Git repository at GitHub] for your own use and
updates.

Contribute your fixes and new features back to the main codebase using
http://help.github.com/articles/using-pull-requests[GitHub pull requests].

== Support

Let me know if you are using JDBC over SSH in your project.

https://github.com/vidakovic[Contact me] if you have questions about the usage, or just like to say something about it.

== Acknowledgements

TBD

== Copyright and license

Copyright 2015 Monkeys in Town Lda.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this work except in compliance with the License.
You may obtain a copy of the License in the LICENSE file, or at:

http://www.apache.org/licenses/LICENSE-2.0[http://www.apache.org/licenses/LICENSE-2.0]

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.